### ISSUE TITLE
docker-compose.yamlの修正

### ISSUE THREAD

**Issue by dumblepy** [Mameta29/fastify-todo-server#12]
ファイル名は `compose.yaml` にする

---

```yaml
app:
  build:
    context: .
    dockerfile: ./Dockerfile
  tty: true
  ports:
    - '8080:8080'
  # volumes:
  #   - .:/app
  environment:
    - DATABASE_URL=postgresql://postgres:password@db:5432/fastifytodo
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PORT=8080
  depends_on:
    - redis
    - db
```
これにしているとホストとコンテナでソースコードのマウントができないので、volumesのコメントは外す

---

adminerを使う
https://github.com/jcam1/payment-detection/blob/main/compose.yaml#L11-L17

---

DBにはadminerを経由してアクセスするので、ホストへのポートの露出はしない
```yaml
db:
  image: postgres:14
  container_name: my_postgres_db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: fastifytodo
  ports:
    - '5432:5432'
```
ports部分を消す
